### ISSUE TITLE
Commit history

### ISSUE THREAD

**Issue by lucymonie** [smarthutza/week6-AMMPazon#48]
For your next project, I'd like to see a greater separation of concerns in your commits. Many of them covered a number of issues. Try to keep them granular, remember the ideal is one commit per pomodoro 

Also, the commit history shows slightly uneven involvement in making commits - try to make sure you switch drivers regularly and share around the making of commits and the job of merging things in

**Comment by PiotrBerebecki** [comment]
Thank, will do.
